import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Trine | Verify emaill",
  description: "Generated by create next app",
};

const VerifyEmail = () => {
  return <div>VerifyEmail</div>;
};

export default VerifyEmail;
