import { Metadata } from "next";
import React from "react";
import styles from "./page.module.scss";
import Forgot from "@/components/auth/ForgotPassword/ForgotPassword";
import AuthentificatedRoute from "@/hoc/withAuthentificated";

export const metadata: Metadata = {
  title: "Auth | Forgot password",
  description: "Generated by create next app",
};

const ForgotPassword = () => {
  return (
    <AuthentificatedRoute>
      <div className={styles.forgotPassword}>
        <div className={styles.screen}>
          <Forgot />
        </div>
      </div>
    </AuthentificatedRoute>
  );
};

export default ForgotPassword;
