import Image from "next/image";
import styles from "./page.module.scss";
import { Metadata } from "next";
import Header from "@/components/Header/Header";
import RoomsView from "@/components/RoomsView/RoomsView";
import Modal from "@/components/modal/Modal";
import ModalsView from "@/components/ModalsView/ModalsView";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className={styles.home}>
      <div className={styles.screen}>
        <div className={styles.background}></div>
        <div className={styles.main}>
          <Header />
          <RoomsView />
          <ModalsView />
        </div>
      </div>
    </main>
  );
}
