import styles from "./page.module.scss";
import { Metadata } from "next";
import Header from "@/components/Header/Header";
import RoomsView from "@/components/RoomsView/RoomsView";
import Modal from "@/components/modal/Modal";
import ModalsView from "@/components/ModalsView/ModalsView";
import AdminNavigation, {
  AdminNavigationCustomButton,
} from "@/components/AdminNavigation/AdminNavigation";
import PrivateRoute from "@/hoc/withAuth";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

function Home() {
  return (
    <PrivateRoute>
      <main className={styles.home}>
        <div className={styles.screen}>
          <div className={styles.background}></div>
          <div className={styles.main}>
            <Header />
            <AdminNavigation title="Колесо фортуни">
              <AdminNavigationCustomButton src="/assets/admin/dropdown/wheel-of-fortune.svg">
                Крутити
              </AdminNavigationCustomButton>
            </AdminNavigation>
            <RoomsView />
            <ModalsView />
          </div>
        </div>
      </main>
    </PrivateRoute>
  );
}

export default Home;
