import { Metadata } from "next";
import React, { ChangeEvent } from "react";
import styles from "./page.module.scss";
import AuthRegistration from "@/components/auth/AuthRegistration/AuthRegistration";
import AuthentificatedRoute from "@/hoc/withAuthentificated";

export const metadata: Metadata = {
  title: "Auth | Registration",
  description: "Generated by create next app",
};

const Registration = () => {
  return (
    <AuthentificatedRoute>
      <div className={styles.registration}>
        <div className={styles.screen}>
          <AuthRegistration />
        </div>
      </div>
    </AuthentificatedRoute>
  );
};

export default Registration;
