import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Trine | Recovery password",
  description: "Generated by create next app",
};

const RecoveryPassword = () => {
  return <div>RecoveryPassword</div>;
};

export default RecoveryPassword;
