import AuthentificatedRoute from "@/hoc/withAuthentificated";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Trine | Recovery password",
  description: "Generated by create next app",
};

const RecoveryPassword = () => {
  return (
    <AuthentificatedRoute>
      <div>RecoveryPassword</div>;
    </AuthentificatedRoute>
  );
};

export default RecoveryPassword;
