import { Metadata } from "next";
import React from "react";
import styles from "./page.module.scss";
import AuthLogin from "@/components/auth/AuthLogin/AuthLogin";
import AuthentificatedRoute from "@/hoc/withAuthentificated";

export const metadata: Metadata = {
  title: "Auth | Login",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <AuthentificatedRoute>
      <div className={styles.login}>
        <div className={styles.screen}>
          <AuthLogin />
        </div>
      </div>
    </AuthentificatedRoute>
  );
};

export default Login;
