import { Metadata } from "next";
import React from "react";
import styles from "./page.module.scss";
import AuthLogin from "@/components/auth/AuthLogin/AuthLogin";

export const metadata: Metadata = {
  title: "Auth | Login",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <div className={styles.login}>
      <div className={styles.screen}>
        <AuthLogin />
      </div>
    </div>
  );
};

export default Login;
